import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Route, Switch, useLocation } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";
import {
  Home,
  ServicesPage,
  ServiceDetailPage,
  WorkPage,
  ProjectDetailPage,
  AboutPage,
  InsightsPage,
  InsightDetailPage,
  StartPage,
  LegalPage,
  NotFoundPage,
} from "./pages/SitePages";
import { useEffect } from "react";
import { CLIENT_ROUTE_META, SITE_URL } from "@shared/routeMeta";
const OG_IMAGE = `${SITE_URL}/og-image.png`;
const OG_IMAGE_ALT =
  "The Web3 Wizard: AI-Native Web3 Product Studio. Turn your Web3 problem into a working product.";

/**
 * MetaManager keeps <head> metadata in sync during client-side navigation.
 * The static HTML files (generated by the SSG plugin at build time) already
 * contain the correct meta for the initial page load, so this component only
 * needs to update tags after the SPA router navigates to a new route.
 */
function MetaManager() {
  const [location] = useLocation();

  useEffect(() => {
    const path = location.split("?")[0].replace(/\/$/, "") || "/";
    const meta = CLIENT_ROUTE_META[path];
    if (!meta) return;

    const { title, description } = meta;
    const canonical = `${SITE_URL}${path === "/" ? "" : path}`;

    document.title = title;

    const setMetaName = (name: string, content: string) => {
      let tag = document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);
      if (!tag) {
        tag = document.createElement("meta");
        tag.name = name;
        document.head.appendChild(tag);
      }
      tag.content = content;
    };
    const setMetaProp = (property: string, content: string) => {
      let tag = document.querySelector<HTMLMetaElement>(`meta[property="${property}"]`);
      if (!tag) {
        tag = document.createElement("meta");
        tag.setAttribute("property", property);
        document.head.appendChild(tag);
      }
      tag.content = content;
    };

    setMetaName("description", description);
    setMetaProp("og:title", title);
    setMetaProp("og:description", description);
    setMetaProp("og:type", "website");
    setMetaProp("og:url", canonical);
    setMetaProp("og:image", OG_IMAGE);
    setMetaProp("og:image:width", "1200");
    setMetaProp("og:image:height", "630");
    setMetaProp("og:image:alt", OG_IMAGE_ALT);
    setMetaProp("og:site_name", "The Web3 Wizard");
    setMetaName("twitter:card", "summary_large_image");
    setMetaName("twitter:title", title);
    setMetaName("twitter:description", description);
    setMetaName("twitter:image", OG_IMAGE);
    setMetaName("twitter:image:alt", OG_IMAGE_ALT);
    setMetaName("twitter:site", "@theweb3wizard00");

    let canonical_el = document.querySelector<HTMLLinkElement>('link[rel="canonical"]');
    if (!canonical_el) {
      canonical_el = document.createElement("link");
      canonical_el.rel = "canonical";
      document.head.appendChild(canonical_el);
    }
    canonical_el.href = canonical;
  }, [location]);

  return null;
}

function Router() {
  return (
    <Switch>
      <Route path="/" component={Home} />
      <Route path="/services" component={ServicesPage} />
      <Route path="/services/product-discovery">
        <ServiceDetailPage type="productDiscovery" />
      </Route>
      <Route path="/services/web3-mvp-development">
        <ServiceDetailPage type="web3MvpDevelopment" />
      </Route>
      <Route path="/services/ai-agent-solana-engineering">
        <ServiceDetailPage type="aiAgentSolanaEngineering" />
      </Route>
      <Route path="/work" component={WorkPage} />
      <Route path="/work/:slug" component={ProjectDetailPage} />
      <Route path="/about" component={AboutPage} />
      <Route path="/insights" component={InsightsPage} />
      <Route path="/insights/:slug" component={InsightDetailPage} />
      <Route path="/start" component={StartPage} />
      <Route path="/privacy">
        <LegalPage kind="privacy" />
      </Route>
      <Route path="/terms">
        <LegalPage kind="terms" />
      </Route>
      <Route component={NotFoundPage} />
    </Switch>
  );
}

export default function App() {
  return (
    <ErrorBoundary>
      <ThemeProvider defaultTheme="dark">
        <TooltipProvider>
          <Toaster />
          <Analytics />
          <MetaManager />
          <Router />
        </TooltipProvider>
      </ThemeProvider>
    </ErrorBoundary>
  );
}
